stages:
  - build
  - deploy

.tsuru_template: &tsuru_template
  image: docker.artifactory.globoi.com/devops-infra/terraform-tsuru:latest
  variables:
    USER: gitlab-ci
  before_script:
    - git config --global user.name adtech-operative-ci
    - git config --global user.email adtech-operative-ci
    - tsuru version

build_dev:
  image: node:15.5.1-alpine
  stage: build
  tags:
    - adtech
    - dc-cm
    - hw
  script:
    - node --version
    - yarn --version
    - yarn config set registry https://artifactory.globoi.com/artifactory/api/npm/npm-repos
    - yarn
    - yarn build-storybook
  artifacts:
    paths:
      - storybook-static/
  only:
    - master

# Deploy para o ambiente de desenvolvimento
deploy_dev:
  <<: *tsuru_template
  stage: deploy
  tags:
    - adtech
    - dc-cm
    - hw
  script:
    - cp -R storybook-static/* tsuru/
    - cd tsuru/
    - make deploy-dev
    - make info-dev
  dependencies: 
    - build_dev
  only:
    - master

